### ISSUE TITLE
[SUGGEST] HexColor Support

### ISSUE THREAD

**Issue by Msyial** [Norbit4/PlayerMarket#2]
# Like This
![QQ_1722335503442](https://github.com/user-attachments/assets/0ba060b0-1a26-478d-84e8-2eda0a4e51d8)
![QQ_1722335511277](https://github.com/user-attachments/assets/95bd51c8-075b-4cd2-a08e-a3b00b152a27)

**Comment by Norbit4** [comment]
Added
